ARG MIRROR=dockerhub.timeweb.cloud
ARG MYSQL_VERSION=8.3.0

FROM ${MIRROR}/mysql:${MYSQL_VERSION}

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
