import os

CURRENTDIRECTORY = os.getcwd()

# defaults
DEFAULTDELIMITER = '~'
DEFAULTBACKUPDIRECTORY = os.path.join(CURRENTDIRECTORY, 'backup')

DEFAULTUSERSDIRECTORY = os.path.join(CURRENTDIRECTORY, 'db', 'users')
DEFAULTUSERSDB = os.path.join(DEFAULTUSERSDIRECTORY, 'users.db')

DEFAULTARTICLEDIRECTORY = os.path.join(CURRENTDIRECTORY, 'db', 'articles')
DEFAULTARTICLESDB = os.path.join(DEFAULTARTICLEDIRECTORY, 'articles.db')

DEFAULTCOMMENTSDIRECTORY = os.path.join(CURRENTDIRECTORY, 'db', 'comments')
DEFAULTCOMMENTSDB = os.path.join(DEFAULTCOMMENTSDIRECTORY, 'comments.db')


# current config
DELIMITER = DEFAULTDELIMITER
ARTICLES_PER_PAGE = 5
BACKUPDIRECTORY = DEFAULTBACKUPDIRECTORY

USERSDIRECTORY = DEFAULTUSERSDIRECTORY
USERSDB = DEFAULTUSERSDB
USERSIDNAME = 'login'
USERSTABLENAME = 'users'

ARTICLEDIRECTORY = DEFAULTARTICLEDIRECTORY
ARTICLESDB = DEFAULTARTICLESDB
ARTICLESIDNAME = 'article_id'
ARTICLESTABLENAME = 'articles'

COMMENTSDB = DEFAULTCOMMENTSDB
COMMENTSDIRECTORY = DEFAULTCOMMENTSDIRECTORY
COMMENTSIDNAME = 'comment_id'
COMMENTSTABLENAME = 'comments'