import os

CURRENTDIRECTORY = os.getcwd()

# defaults
DEFAULTDELIMITER = '~'
DEFAULTBACKUPDIRECTORY = os.path.join(CURRENTDIRECTORY, 'backup')
DEFAULTUSERSDIRECTORY = os.path.join(CURRENTDIRECTORY, 'db', 'users')
DEFAULTUSERSDB = os.path.join(DEFAULTUSERSDIRECTORY, 'users.db')
DEFAULTARTICLEDIRECTORY = os.path.join(CURRENTDIRECTORY, 'db', 'articles')
DEFAULTARTICLESDB = os.path.join(DEFAULTARTICLEDIRECTORY, 'articles.db')

# current config
DELIMITER = DEFAULTDELIMITER
BACKUPDIRECTORY = DEFAULTBACKUPDIRECTORY
USERSDIRECTORY = DEFAULTUSERSDIRECTORY
USERSDB = DEFAULTUSERSDB
ARTICLEDIRECTORY = DEFAULTARTICLEDIRECTORY
ARTICLESDB = DEFAULTARTICLESDB